import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
(function() {
	// Polyfill 1: import.meta.url
	try {
		if (typeof __filename !== 'undefined' && __filename) {
			var pathToFileURL = require('url').pathToFileURL;
			globalThis.import_meta_url = pathToFileURL(__filename).href;
		} else {
			globalThis.import_meta_url = 'file:///obsidian-plugin/main.js';
		}
	} catch (e) {
		console.error('[import.meta.url polyfill] Error:', e);
		globalThis.import_meta_url = 'file:///obsidian-plugin/main.js';
	}

	// Polyfill 2: events.setMaxListeners with AbortSignal support (Node.js 18+ feature)
	try {
		var events = require('events');
		var originalSetMaxListeners = events.setMaxListeners;
		if (originalSetMaxListeners) {
			events.setMaxListeners = function(n, ...eventTargets) {
				try {
					return originalSetMaxListeners.call(events, n, ...eventTargets);
				} catch (err) {
					// Silently ignore AbortSignal errors in older Node.js versions
					if (err && err.code === 'ERR_INVALID_ARG_TYPE' &&
						err.message && err.message.includes('AbortSignal')) {
						return;
					}
					throw err;
				}
			};
		}
	} catch (e) {
		console.error('[setMaxListeners polyfill] Error:', e);
	}
})();
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	define: {
		'import.meta.url': 'globalThis.import_meta_url',
	},
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
